import os
import sys
import logging
from typing import Dict, List, Tuple
import pandas as pd
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.utils.config import OUTPUT_ROOT, RANDOM_SEED

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(f"{OUTPUT_ROOT}/logs/temporal_split.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

EDGE_DIR = f"{OUTPUT_ROOT}/edges"
SPLITS_DIR = f"{OUTPUT_ROOT}/dgl/splits"
REPORTS_DIR = f"{OUTPUT_ROOT}/reports"
os.makedirs(SPLITS_DIR, exist_ok=True)
os.makedirs(REPORTS_DIR, exist_ok=True)

EDGE_TYPES = ["placement", "r1_suits", "r2_requires", "r3_drives", "r4_shifts"]

# 统一时间切分（所有时序关系共用同一边界）
# 上界 61：受 r2_requires 限制（tau 最大 61），保证 test 段所有关系都有数据
UNIFIED_SPLIT = {
    "train": (1, 49),
    "val":   (50, 55),
    "test":  (56, 61),
}

# r4_shifts 是 τ=-1 的跨窗口边，没有时间维度，完全排除（不参与 RE-GCN 时序建模）
EXCLUDE_FROM_SPLIT = ["r4_shifts"]


def load_all_edges() -> Dict[str, pd.DataFrame]:
    """Load all edge parquet files."""
    logger.info("Loading all edges...")
    
    edges = {}
    for edge_type in EDGE_TYPES:
        df = pd.read_parquet(f"{EDGE_DIR}/{edge_type}_edges.parquet")
        edges[edge_type] = df
        logger.info(f"  {edge_type}: {len(df):,} edges, cols: {df.columns.tolist()}")
    
    return edges


def split_edges_by_relation(
    edges: Dict[str, pd.DataFrame]
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    统一时间切分（所有时序关系共用同一边界）:
        Train τ ∈ [1, 49] / Val τ ∈ [50, 55] / Test τ ∈ [56, 61]
    r4_shifts (τ=-1) 整个跳过，不进任何 split。
    """
    logger.info("统一时间切分: train[1,49] val[50,55] test[56,61]，排除 r4_shifts")
    train_edges, val_edges, test_edges = [], [], []

    for edge_type, df in edges.items():
        if edge_type in EXCLUDE_FROM_SPLIT:
            logger.info(f"  {edge_type}: 跳过（非时序边）")
            continue
        df = df.copy()
        df["edge_type"] = edge_type
        df = df[df["tau"] >= 1]  # 过滤 tau=-1 等脏数据

        tr_s, tr_e = UNIFIED_SPLIT["train"]
        v_s, v_e = UNIFIED_SPLIT["val"]
        te_s, te_e = UNIFIED_SPLIT["test"]

        train_df_type = df[(df["tau"] >= tr_s) & (df["tau"] <= tr_e)].copy()
        val_df_type   = df[(df["tau"] >= v_s) & (df["tau"] <= v_e)].copy()
        test_df_type  = df[(df["tau"] >= te_s) & (df["tau"] <= te_e)].copy()

        logger.info(f"  {edge_type}: train={len(train_df_type):,} val={len(val_df_type):,} test={len(test_df_type):,}")
        train_edges.append(train_df_type)
        val_edges.append(val_df_type)
        test_edges.append(test_df_type)

    train_df = pd.concat(train_edges, ignore_index=True) if train_edges else pd.DataFrame()
    val_df = pd.concat(val_edges, ignore_index=True) if val_edges else pd.DataFrame()
    test_df = pd.concat(test_edges, ignore_index=True) if test_edges else pd.DataFrame()
    return train_df, val_df, test_df


def generate_split_report(
    edges: Dict[str, pd.DataFrame],
    train_df: pd.DataFrame,
    val_df: pd.DataFrame,
    test_df: pd.DataFrame
) -> str:
    """Generate the temporal split report in markdown format."""
    logger.info("Generating split report...")
    
    total_train = len(train_df)
    total_val = len(val_df)
    total_test = len(test_df)
    total_all = total_train + total_val + total_test
    
    report = f"""# Temporal Split Report

> Generated by src/temporal_split.py

## Split Configuration (Unified Temporal Boundaries)

| Split | τ range |
|---|---|
| Train | [1, 49] |
| Val   | [50, 55] |
| Test  | [56, 61] |

**Rationale**: 上界 61 受 r2_requires（tau 最大 61）限制，保证 test 段所有时序关系都有数据。
所有时序关系（placement / r1_suits / r2_requires / r3_drives）共用同一边界，
与 RE-GCN 滑动窗口评估范式兼容。r4_shifts (τ=-1) 跨窗口边不参与时序建模，已排除。

## Edge Counts by Relation Type

| Relation Type | Total | Train | Val | Test | All Non-Empty |
|---|---|---|---|---|---|
"""
    
    all_non_empty = True
    for edge_type in EDGE_TYPES:
        df = edges.get(edge_type, pd.DataFrame())
        total = len(df)
        
        train_count = len(train_df[train_df["edge_type"] == edge_type]) if len(train_df) > 0 else 0
        val_count = len(val_df[val_df["edge_type"] == edge_type]) if len(val_df) > 0 else 0
        test_count = len(test_df[test_df["edge_type"] == edge_type]) if len(test_df) > 0 else 0
        
        non_empty = "✅" if (train_count > 0 and val_count > 0 and test_count > 0) else "❌"
        if train_count == 0 or val_count == 0 or test_count == 0:
            all_non_empty = False
        
        report += f"| {edge_type} | {total:,} | {train_count:,} | {val_count:,} | {test_count:,} | {non_empty} |\n"
    
    report += f"\n**Total**: {total_all:,} edges\n"
    
    if all_non_empty:
        report += "\n✅ **All relation types have non-empty train/val/test sets**\n"
    else:
        report += "\n⚠️ **Some relation types have empty splits**\n"
    
    report += """
## r4_shifts Exclusion

r4_shifts edges have τ=-1 (cross-window), 没有时间维度。
它们不参与 RE-GCN 时序建模，已从所有 split 中完全排除。
"""
    
    return report


def save_splits(
    train_df: pd.DataFrame,
    val_df: pd.DataFrame,
    test_df: pd.DataFrame
):
    """Save split DataFrames to parquet files."""
    logger.info("Saving split parquet files...")
    
    if len(train_df) > 0:
        train_path = f"{SPLITS_DIR}/train_edges.parquet"
        train_df.to_parquet(train_path, index=False)
        logger.info(f"  Saved train: {len(train_df):,} edges to {train_path}")
    else:
        logger.warning("  Train set is empty, no file saved")
    
    if len(val_df) > 0:
        val_path = f"{SPLITS_DIR}/val_edges.parquet"
        val_df.to_parquet(val_path, index=False)
        logger.info(f"  Saved val: {len(val_df):,} edges to {val_path}")
    else:
        logger.warning("  Val set is empty, no file saved")
    
    if len(test_df) > 0:
        test_path = f"{SPLITS_DIR}/test_edges.parquet"
        test_df.to_parquet(test_path, index=False)
        logger.info(f"  Saved test: {len(test_df):,} edges to {test_path}")
    else:
        logger.warning("  Test set is empty, no file saved")


def main():
    logger.info("=" * 60)
    logger.info("Starting temporal split (unified boundaries, exclude r4_shifts)")
    logger.info("=" * 60)
    
    edges = load_all_edges()
    
    train_df, val_df, test_df = split_edges_by_relation(edges)
    
    logger.info(f"\nSplit Summary:")
    logger.info(f"  Train edges: {len(train_df):,}")
    logger.info(f"  Val edges: {len(val_df):,}")
    logger.info(f"  Test edges: {len(test_df):,}")
    
    save_splits(train_df, val_df, test_df)
    
    report = generate_split_report(edges, train_df, val_df, test_df)
    report_path = f"{REPORTS_DIR}/temporal_split.md"
    with open(report_path, "w") as f:
        f.write(report)
    logger.info(f"  Saved report to {report_path}")
    
    print("\n" + "=" * 60)
    print("TEMPORAL SPLIT SUMMARY")
    print("=" * 60)
    print(f"Train edges: {len(train_df):,}")
    print(f"Val edges: {len(val_df):,}")
    print(f"Test edges: {len(test_df):,}")
    print(f"\nPer-relation split:")
    for edge_type in EDGE_TYPES:
        train_c = len(train_df[train_df["edge_type"] == edge_type]) if len(train_df) > 0 else 0
        val_c = len(val_df[val_df["edge_type"] == edge_type]) if len(val_df) > 0 else 0
        test_c = len(test_df[test_df["edge_type"] == edge_type]) if len(test_df) > 0 else 0
        print(f"  {edge_type}: train={train_c:,}, val={val_c:,}, test={test_c:,}")
    print(f"\nReport saved to: {report_path}")
    print("=" * 60)
    
    logger.info("=" * 60)
    logger.info("Temporal split complete")
    logger.info("=" * 60)
    
    return train_df, val_df, test_df


if __name__ == "__main__":
    main()